### PR TITLE
Implements https://github.com/sul-dlss/stanford-mods/issues/66

### PR DESCRIPTION
**Pull request by lmcglohon**
@ndushay For genre, these are the facet values we want: Government document, Conference proceedings, Technical report and Thesis/Dissertation

For geodata, the resource type should be only Map and not include Software, multimedia.

### CODE REVIEW

**Comment by ndushay** [comment]
One concern I have about testing / comments:   we do have MODS with something in genre field we don't want for searchworks -- see feigenbaum collection, for example.   We probably want a test showing unwanted values will not appear in sw_genre results (and code ensuring this is true, of course).

**Comment by ndushay** [comment]
BTW, one way to associate a PR with an issue in the same git repo is to name the branch starting with the issue number, like  66-genre-values.  Then I think github automagically associates PR with the issue and I believe waffle will also based on github.

This practice also defaults to a more informative PR title.

**Comment by lmcglohon** [comment]
@ndushay the list of unwanted values for sw_genre is unknown and probably infinite.  Shall I just test for a fake value like "Fake value"?  Or do you mean something else.

As far as the code goes, do you not believe it will exclude values other than the four values included?

**Comment by ndushay** [comment]
@lmcglohon right, just have a test for a single unwanted value like "unwanted value".

**Pull request merged**
